platform :ios, "7.1"

source 'https://github.com/CocoaPods/Specs.git'

# 忽略三方库警告
inhibit_all_warnings!

def public_pods
    # 网络请求
    pod 'AFNetworking', '3.1.0'

    # 自动布局
    pod 'Masonry', '0.6.2'

    # 字典和模型的互转
    pod 'Mantle', '2.0.5'

    # 图片加载
    pod 'SDWebImage', '3.7.3'

    # “等待框”
    pod 'MBProgressHUD', '0.9.1'

    # 智能键盘
    pod 'IQKeyboardManager', '3.3.7'

    # Categories on NSAttributedString to add a lot of useful convenience methods.
    pod 'OHAttributedStringAdditions', '1.3.0'

    # 富文本的UILabel
    pod 'TTTAttributedLabel', '1.13.4'

    # 带占位符的UITextView
    pod 'UITextView+Placeholder', '1.1.0'

end

target ‘DHNetRequestTool’ do

    public_pods

end
